# Generated by Django 4.0.2 on 2022-02-21 01:21

from django.db import migrations, models



def populate_country(apps, schema_editor):
    names = [
        'Arabic spoken followers',
        'English spoken followers',
        'Turkish spoken followers',
        'Spanish spoken follower',
        'Chinese spoken follower',
        'Russian spoken followers',
        'Asia',
        'Africa',
        'North America',
        'South America',
        'Europe',
        'Antarctica Oceania',
    ]
    Country = apps.get_model('api', 'Country')
    for name in names:
        obj = Country(name=name)
        obj.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RunPython(populate_country),
    ]
